routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
})->middleware('guest');

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

// USER ROUTE
Route::group(['prefix' => 'users', 'as' => 'users.'], function() {
    Route::get('/', [UserController::class, 'index'])->name('list');
    Route::get('/user-list', [UserController::class, 'getUsers'])->name('fetchdata');

    Route::get('/add', [UserController::class, 'createView'])->name('createView');
    Route::post('/add', [UserController::class, 'create'])->name('create');

    Route::get('/edit/{id}', [UserController::class, 'updateView'])->name('updateView');
    Route::patch('/edit/{id}', [UserController::class, 'update'])->name('update');

    Route::delete('/delete/{id}', [UserController::class, 'delete'])->name('delete');
});

// PROJECTS ROUTE
Route::group(['prefix' => 'projects', 'as' => 'projects.'], function() {
    Route::get('/', [ProjectController::class, 'index'])->name('list');
    Route::get('/project-list', [ProjectController::class, 'getprojects'])->name('fetchdata');

    Route::get('/add', [ProjectController::class, 'createView'])->name('createView');
    Route::post('/add', [ProjectController::class, 'create'])->name('create');

    Route::get('/edit/{id}', [ProjectController::class, 'updateView'])->name('updateView');
    Route::patch('/edit/{id}', [ProjectController::class, 'update'])->name('update');

    Route::delete('/delete/{id}', [ProjectController::class, 'delete'])->name('delete');
});

app/Models/Project.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    use HasFactory;

    public $timestamp = false;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */

    protected $guarded = ['id'];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'deleted_at' => 'datetime',
    ];
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Project;
use App\Traits\AuditTrails;
use Illuminate\Validation\Rule;
use Illuminate\Support\Facades\Auth;
use DataTables;

class ProjectController extends Controller
{
    use AuditTrails;
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('layouts.projects.index');
    }

    public function getProjects(Request $request) {
        if ($request->ajax()) {
            $data = Project::latest()->where('deleted_at', null)->get();
            return Datatables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function($row){
                    $actionBtn = '<a href="'.route('projects.updateView', [$row->id]).'" class="edit btn btn-warning btn-sm text-light">Edit</a>
                                  <form action="'.route('projects.delete', [$row->id]).'" method="POST" style="display: contents;">
                                    <input type="hidden" name="_method" value="DELETE">
                                    <button class="delete btn btn-danger btn-sm" title="Delete" >Delete</button>
                                  </form>';
                    return $actionBtn;
                })
                ->rawColumns(['action'])
                ->make(true);
        }
    }

    public function createView() {
        return view('layouts.projects.add');
    }

    public function create(Request $request) {
        $data = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'description' => ['required', 'string'],
            'start_at' => ['required', 'date', 'after:today'],
            'finish_at' => ['required', 'date', 'after_or_equal:start_at']
        ]);

        $project = Project::create([
            'name' => $data['name'],
            'description' => $data['description'],
            'start_at' => $data['start_at'],
            'finish_at' => $data['finish_at']
        ]);

        $project = $this->setCreatedAuditTrails($project);
        $project->save();

        return redirect()->route('projects.list')->with('success', 'Success adding new project.');
    }

    public function updateView($id) {
        $project = Project::findOrFail($id);
        return view('layouts.projects.edit', compact('project'));
    }

    public function update(Request $request, $id) {
        $project = project::findOrFail($id);

        $data = $request->validate([
            'name' => ['string', 'max:255'],
            'description' => ['string'],
            'start_at' => ['nullable', 'date', 'after:today'],
            'finish_at' => ['nullable', 'date', 'after_or_equal:start_at']
        ]);

        $project->name = $data['name'] === null || $data['name'] === '' ? $project->name : $data['name'];
        $project->description = $data['description'] === null || $data['description'] === '' ? $project->description : $data['description'];
        $project->start_at = $data['start_at'] === null || $data['start_at'] === '' ? $project->start_at : $data['start_at'];
        $project->finish_at = $data['finish_at'] === null || $data['finish_at'] === '' ? $project->finish_at : $data['finish_at'];
        $project = $this->setUpdatedAuditTrails($project);

        $project->save();

        return redirect()->route('projects.list')->with('success', 'Success edit existing project.');
    }

    public function delete($id) {
        $project = Project::findOrFail($id);

        $project = $this->setDeletedAuditTrails($project);
        $project->save();
        return redirect()->route('projects.list')->with('success', 'Success deleting project '.$project->name.'.');
    }
}

resources/views/layouts/projects/add.blade.php
@extends('adminlte::page')

@section('title', 'Project')

@section('content_header')
    <h1>Create New Project</h1>
@stop

@section('content')
    <x-adminlte-card title="Form Create Project" theme="dark" icon="fas fa-lg fa-suitcase" collapsible>
        <form action="{{ route('projects.create') }}" method="post">
            @csrf

            <div class="row">
                <div class="col-md-6">
                    {{-- Name field --}}
                    <div class="input-group mb-3">
                        <input type="text" name="name" class="form-control @error('name') is-invalid @enderror"
                            value="{{ old('name') }}" placeholder="{{ 'Project Name...' }}" autofocus>

                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-suitcase {{ config('adminlte.classes_auth_icon', '') }}"></span>
                            </div>
                        </div>

                        @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
                <div class="col-md-6">
                    {{-- Description field --}}
                    <div class="input-group mb-3">
                        <input type="text" name="description" class="form-control @error('description') is-invalid @enderror"
                            value="{{ old('description') }}" placeholder="{{ 'Project Description...' }}">

                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-file-alt {{ config('adminlte.classes_auth_icon', '') }}"></span>
                            </div>
                        </div>

                        @error('description')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    {{-- Start date field --}}
                    <div class="input-group mb-3">
                        <input type="date" name="start_at" class="form-control @error('start_at') is-invalid @enderror">

                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-calendar {{ config('adminlte.classes_auth_icon', '') }}"></span>
                            </div>
                        </div>

                        @error('start_at')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
                <div class="col-md-6">
                    {{-- Finish date field --}}
                    <div class="input-group mb-3">
                        <input type="date" name="finish_at"
                            class="form-control @error('finish_at') is-invalid @enderror">

                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-calendar {{ config('adminlte.classes_auth_icon', '') }}"></span>
                            </div>
                        </div>

                        @error('finish_at')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
            </div>

            {{-- Register button --}}
            <button type="submit" class="btn btn-block {{ config('adminlte.classes_auth_btn', 'btn-flat btn-primary') }}">
                <span class="fas fa-user-plus"></span>
                {{ "Submit" }}
            </button>

        </form>

    </x-adminlte-card>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script>
     </script>
@stop

resources/views/layouts/projects/edit.blade.php
@extends('adminlte::page')

@section('title', 'Project')

@section('content_header')
    <h1>Edit Project</h1>
@stop

@section('content')
    <x-adminlte-card title="Form Create Project" theme="dark" icon="fas fa-lg fa-suitcase" collapsible>
        <form action="{{ route('projects.update', $project->id) }}" method="post">
            @csrf
            {{ method_field('PATCH') }}

            <div class="row">
                <div class="col-md-6">
                    {{-- Name field --}}
                    <div class="input-group mb-3">
                        <input type="text" name="name" class="form-control @error('name') is-invalid @enderror"
                            value="{{ $project->name }}" placeholder="{{ 'Project Name...' }}" autofocus>

                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-suitcase {{ config('adminlte.classes_auth_icon', '') }}"></span>
                            </div>
                        </div>

                        @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
                <div class="col-md-6">
                    {{-- Description field --}}
                    <div class="input-group mb-3">
                        <input type="text" name="description" class="form-control @error('description') is-invalid @enderror"
                            value="{{ $project->description }}" placeholder="{{ 'Project Description...' }}">

                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-file-alt {{ config('adminlte.classes_auth_icon', '') }}"></span>
                            </div>
                        </div>

                        @error('description')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    {{-- Start date field --}}
                    <div class="input-group mb-3">
                        <input type="date" name="start_at" class="form-control @error('start_at') is-invalid @enderror"
                        value="{{ $project->start_at }}">

                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-calendar {{ config('adminlte.classes_auth_icon', '') }}"></span>
                            </div>
                        </div>

                        @error('start_at')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
                <div class="col-md-6">
                    {{-- Finish date field --}}
                    <div class="input-group mb-3">
                        <input type="date" name="finish_at"
                            class="form-control @error('finish_at') is-invalid @enderror" value="{{ $project->finish_at }}">

                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-calendar {{ config('adminlte.classes_auth_icon', '') }}"></span>
                            </div>
                        </div>

                        @error('finish_at')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
            </div>

            {{-- Register button --}}
            <button type="submit" class="btn btn-block {{ config('adminlte.classes_auth_btn', 'btn-flat btn-primary') }}">
                <span class="fas fa-user-plus"></span>
                {{ "Submit" }}
            </button>

        </form>

    </x-adminlte-card>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script>
     </script>
@stop

resources/views/layouts/projects/index.blade.php
@extends('adminlte::page')

@section('title', 'Projects')

@section('content_header')
    <h1>List All Projects</h1>
@stop

@section('content')
    <x-adminlte-card title="Projects Table" theme="dark" icon="fas fa-lg fa-suitcase" collapsible>

        @if (\Session::has('success'))
            <x-adminlte-alert theme="info" title="Success">
                {!! \Session::get('success') !!}
            </x-adminlte-alert>
        @endif

        @error('msg')
            <x-adminlte-alert theme="danger" title="Warning">
                {!! $message !!}
            </x-adminlte-alert>
        @enderror

        <a href="{{ route('projects.createView') }}" class="edit btn btn-flat btn-success mb-3">Tambah Project</a>

        <table class="table table-bordered yajra-datatable">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Start Date</th>
                    <th>Finish Date</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>

    </x-adminlte-card>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script>
        $(function () {

            var table = $('.yajra-datatable').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ route('projects.fetchdata') }}",
                columns: [
                    {data: 'DT_RowIndex', name: 'DT_RowIndex'},
                    {data: 'name', name: 'name'},
                    {data: 'description', name: 'description'},
                    {data: 'start_at', name: 'start_at'},
                    {data: 'finish_at', name: 'finish_at'},
                    {
                        data: 'action',
                        name: 'action',
                        orderable: true,
                        searchable: true
                    },
                ]
            });

        });
     </script>
@stop