routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
})->middleware('guest');

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

// USER ROUTE
Route::group(['prefix' => 'users', 'as' => 'users.'], function() {
    Route::get('/', [UserController::class, 'index'])->name('list');
    Route::get('/user-list', [UserController::class, 'getUsers'])->name('fetchdata');

    Route::get('/add', [UserController::class, 'createView'])->name('createView');
    Route::post('/add', [UserController::class, 'create'])->name('create');

    Route::get('/edit/{id}', [UserController::class, 'updateView'])->name('updateView');
    Route::patch('/edit/{id}', [UserController::class, 'update'])->name('update');

    Route::delete('/delete/{id}', [UserController::class, 'delete'])->name('delete');
});

// PROJECTS ROUTE
Route::group(['prefix' => 'projects', 'as' => 'projects.'], function() {
    Route::get('/', [ProjectController::class, 'index'])->name('list');
    Route::get('/project-list', [ProjectController::class, 'getprojects'])->name('fetchdata');

    Route::get('/add', [ProjectController::class, 'createView'])->name('createView');
    Route::post('/add', [ProjectController::class, 'create'])->name('create');

    Route::get('/edit/{id}', [ProjectController::class, 'updateView'])->name('updateView');
    Route::patch('/edit/{id}', [ProjectController::class, 'update'])->name('update');

    Route::delete('/delete/{id}', [ProjectController::class, 'delete'])->name('delete');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    public $timestamp = false;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */

    protected $guarded = ['id'];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'deleted_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;
use App\Traits\AuditTrails;
use Illuminate\Validation\Rule;
use Illuminate\Support\Facades\Auth;
use DataTables;

class UserController extends Controller
{
    use AuditTrails;
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('layouts.users.index');
    }

    public function getUsers(Request $request) {
        if ($request->ajax()) {
            $data = User::latest()->where('deleted_at', null)->get();
            return Datatables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function($row){
                    $actionBtn = '<a href="'.route('users.updateView', [$row->id]).'" class="edit btn btn-warning btn-sm text-light">Edit</a>
                                  <form action="'.route('users.delete', [$row->id]).'" method="POST" style="display: contents;">
                                    <input type="hidden" name="_method" value="DELETE">
                                    <button class="delete btn btn-danger btn-sm" title="Delete" >Delete</button>
                                  </form>';
                    return $actionBtn;
                })
                ->rawColumns(['action'])
                ->make(true);
        }
    }

    public function createView() {
        return view('layouts.users.add');
    }

    public function create(Request $request) {
        $data = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
            'role' => ['required'],
        ]);

        $user = User::create([
            'name' => $data['name'],
            'email' => $data['email'],
            'password' => bcrypt($data['password']),
            'role' => $data['role']
        ]);

        $user = $this->setCreatedAuditTrails($user);
        $user->save();

        return redirect()->route('users.list')->with('success', 'Success adding new user.');
    }

    public function updateView($id) {
        $user = User::findOrFail($id);
        return view('layouts.users.edit', compact('user'));
    }

    public function update(Request $request, $id) {
        $user = User::findOrFail($id);

        $data = $request->validate([
            'name' => ['string', 'max:255'],
            'email' => ['string', 'email', 'max:255', Rule::unique('users')->ignore($user->id)],
            'password' => ['nullable', 'string', 'min:8', 'confirmed'],
            'role' => ['required'],
        ]);

        $user->name = $data['name'] === null || $data['name'] === '' ? $user->name : $data['name'];
        $user->email = $data['email'] === null || $data['email'] === '' ? $user->email : $data['email'];
        $user->password = $data['password'] === null || $data['password'] === '' ? $user->email : bcrypt($data['password']);
        $user->role = $data['role'];
        $user = $this->setUpdatedAuditTrails($user);

        $user->save();

        return redirect()->route('users.list')->with('success', 'Success edit existing user.');
    }

    public function delete($id) {
        $user = User::findOrFail($id);
        if ($user->email === Auth::user()->email) {
            return redirect()->route('users.list')->withErrors([
                'msg' => 'User is logged in'
            ]);
        }

        $user = $this->setDeletedAuditTrails($user);
        $user->save();
        return redirect()->route('users.list')->with('success', 'Success deleting user '.$user->name.'.');
    }
}

resources/views/layouts/users/add.blade.php
@extends('adminlte::page')

@section('title', 'Users')

@section('content_header')
    <h1>Create New User</h1>
@stop

@section('content')
    <x-adminlte-card title="Form Create User" theme="dark" icon="fas fa-lg fa-users" collapsible>
        <form action="{{ route('users.create') }}" method="post">
            @csrf

            <div class="row">
                <div class="col-md-6">
                    {{-- Name field --}}
                    <div class="input-group mb-3">
                        <input type="text" name="name" class="form-control @error('name') is-invalid @enderror"
                            value="{{ old('name') }}" placeholder="{{ __('adminlte::adminlte.full_name') }}" autofocus>

                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-user {{ config('adminlte.classes_auth_icon', '') }}"></span>
                            </div>
                        </div>

                        @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
                <div class="col-md-6">
                    {{-- Email field --}}
                    <div class="input-group mb-3">
                        <input type="email" name="email" class="form-control @error('email') is-invalid @enderror"
                            value="{{ old('email') }}" placeholder="{{ __('adminlte::adminlte.email') }}">

                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-envelope {{ config('adminlte.classes_auth_icon', '') }}"></span>
                            </div>
                        </div>

                        @error('email')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    {{-- Password field --}}
                    <div class="input-group mb-3">
                        <input type="password" name="password" class="form-control @error('password') is-invalid @enderror"
                            placeholder="{{ __('adminlte::adminlte.password') }}">

                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock {{ config('adminlte.classes_auth_icon', '') }}"></span>
                            </div>
                        </div>

                        @error('password')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
                <div class="col-md-6">
                    {{-- Confirm password field --}}
                    <div class="input-group mb-3">
                        <input type="password" name="password_confirmation"
                            class="form-control @error('password_confirmation') is-invalid @enderror"
                            placeholder="{{ __('adminlte::adminlte.retype_password') }}">

                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock {{ config('adminlte.classes_auth_icon', '') }}"></span>
                            </div>
                        </div>

                        @error('password_confirmation')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <x-adminlte-select2 name="role" igroup-size="md">
                        <x-slot name="appendSlot">
                            <div class="input-group-text">
                                <i class="fas fa-briefcase"></i>
                            </div>
                        </x-slot>
                        <option value="" selected disabled hidden>Pilih Role...</option>
                        <option value="ADMIN">Admin</option>
                        <option value="USER">User</option>
                    </x-adminlte-select2>

                    @error('role')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
            </div>

            {{-- Register button --}}
            <button type="submit" class="btn btn-block {{ config('adminlte.classes_auth_btn', 'btn-flat btn-primary') }}">
                <span class="fas fa-user-plus"></span>
                {{ __('adminlte::adminlte.register') }}
            </button>

        </form>

    </x-adminlte-card>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script>
     </script>
@stop

resources/views/layouts/users/edit.blade.php
@extends('adminlte::page')

@section('title', 'Users')

@section('content_header')
    <h1>Edit User</h1>
@stop

@section('content')
    <x-adminlte-card title="Form Create User" theme="dark" icon="fas fa-lg fa-users" collapsible>
        <form action="{{ route('users.update', $user->id) }}" method="post">
            @csrf
            {{ method_field('PATCH') }}

            <div class="row">
                <div class="col-md-6">
                    {{-- Name field --}}
                    <div class="input-group mb-3">
                        <input type="text" name="name" class="form-control @error('name') is-invalid @enderror"
                            value="{{ $user->name }}" placeholder="{{ __('adminlte::adminlte.full_name') }}" autofocus>

                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-user {{ config('adminlte.classes_auth_icon', '') }}"></span>
                            </div>
                        </div>

                        @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
                <div class="col-md-6">
                    {{-- Email field --}}
                    <div class="input-group mb-3">
                        <input type="email" name="email" class="form-control @error('email') is-invalid @enderror"
                            value="{{ $user->email }}" placeholder="{{ __('adminlte::adminlte.email') }}">

                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-envelope {{ config('adminlte.classes_auth_icon', '') }}"></span>
                            </div>
                        </div>

                        @error('email')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    {{-- Password field --}}
                    <div class="input-group mb-3">
                        <input type="password" name="password" class="form-control @error('password') is-invalid @enderror"
                            placeholder="{{ __('adminlte::adminlte.password') }}">

                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock {{ config('adminlte.classes_auth_icon', '') }}"></span>
                            </div>
                        </div>

                        @error('password')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
                <div class="col-md-6">
                    {{-- Confirm password field --}}
                    <div class="input-group mb-3">
                        <input type="password" name="password_confirmation"
                            class="form-control @error('password_confirmation') is-invalid @enderror"
                            placeholder="{{ __('adminlte::adminlte.retype_password') }}">

                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock {{ config('adminlte.classes_auth_icon', '') }}"></span>
                            </div>
                        </div>

                        @error('password_confirmation')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <x-adminlte-select2 name="role" igroup-size="md">
                        <x-slot name="appendSlot">
                            <div class="input-group-text">
                                <i class="fas fa-briefcase"></i>
                            </div>
                        </x-slot>
                        <option value="ADMIN" {{ $user->role === "ADMIN" ? "selected" : "" }}>Admin</option>
                        <option value="USER" {{ $user->role === "USER" ? "selected" : "" }}>User</option>
                    </x-adminlte-select2>

                    @error('role')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
            </div>

            {{-- Register button --}}
            <button type="submit" class="btn btn-block {{ config('adminlte.classes_auth_btn', 'btn-flat btn-primary') }}">
                <span class="fas fa-user-plus"></span>
                {{ 'Edit User' }}
            </button>

        </form>

    </x-adminlte-card>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script>
     </script>
@stop

resources/views/layouts/users/index.blade.php
@extends('adminlte::page')

@section('title', 'Users')

@section('content_header')
    <h1>List All Users</h1>
@stop

@section('content')
    <x-adminlte-card title="Users Table" theme="dark" icon="fas fa-lg fa-users" collapsible>

        @if (\Session::has('success'))
            <x-adminlte-alert theme="info" title="Success">
                {!! \Session::get('success') !!}
            </x-adminlte-alert>
        @endif

        @error('msg')
            <x-adminlte-alert theme="danger" title="Warning">
                {!! $message !!}
            </x-adminlte-alert>
        @enderror

        <a href="{{ route('users.createView') }}" class="edit btn btn-flat btn-success mb-3">Tambah User</a>

        <table class="table table-bordered yajra-datatable">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Role</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>

    </x-adminlte-card>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script>
        $(function () {

            var table = $('.yajra-datatable').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ route('users.fetchdata') }}",
                columns: [
                    {data: 'DT_RowIndex', name: 'DT_RowIndex'},
                    {data: 'name', name: 'name'},
                    {data: 'email', name: 'email'},
                    {data: 'role', name: 'role'},
                    {
                        data: 'action',
                        name: 'action',
                        orderable: true,
                        searchable: true
                    },
                ]
            });

        });
     </script>
@stop